// Bütün məzmun burada — saytı yeniləmək üçün yalnız bu faylı redaktə et.

export const links = {
  email: 'saidmuradkhan414@gmail.com',
  github: 'https://github.com/saidmuradkhan',
  gitlab: 'https://gitlab.com/saidmuradkhan414',
  linkedin: 'https://www.linkedin.com/in/said-muradkhan-0103a2350/',
  cv: '/Said_Muradkhan_CV.pdf',
}

export const marquee = [
  'PHP', 'Laravel', 'React', 'JavaScript', 'Node.js', 'Express', 'MySQL',
  'PostgreSQL', 'REST API', 'Tailwind CSS', 'Docker', 'GitLab CI/CD',
]

export const skillGroups = [
  { key: 'backend', items: ['PHP', 'Laravel', 'Node.js', 'Express', 'REST APIs', 'MVC'] },
  { key: 'frontend', items: ['React', 'JavaScript (ES6+)', 'HTML5', 'CSS3', 'Tailwind CSS', 'Bootstrap', 'i18next'] },
  { key: 'data', items: ['MySQL', 'PostgreSQL', 'SQL'] },
  { key: 'devops', items: ['Git', 'GitHub', 'GitLab', 'CI/CD', 'Docker', 'Composer', 'npm'] },
  { key: 'other', items: ['Python', 'C++', 'Java'] },
]

export const content = {
  name: { first: 'Said', last: 'Muradkhan' },
  nav: { about: 'About', work: 'Experience', projects: 'Projects', skills: 'Skills', contact: 'Contact' },
  loading: 'Loading',
  hero: {
    eyebrow: 'Full-Stack Developer · Baku',
    roles: ['Full-Stack Developer', 'Laravel & React', 'Python'],
    lead: 'I build web applications and internal systems that make a company\'s day-to-day work easier. I work across the front end and back end with one goal: software that is simple, fast and reliable.',
    ctaWork: 'See my work',
    ctaCv: 'Download CV',
    available: 'Open to new opportunities',
    scroll: 'Scroll down',
  },
  about: {
    index: '01',
    title: 'About',
    big: 'I write code not just to work, but to keep working <em>for years</em>.',
    p1: 'I\'m a Computer Science student at Khazar University and a Full-Stack Developer at Leops. I work on systems that run real company operations — from refactoring legacy code to building new products from scratch.',
    p2: 'I\'m comfortable on both sides of the stack: PHP, Laravel, JavaScript, React, SQL and Git. Server configuration and deployment are part of the job too.',
    stats: [
      { n: 7, s: '', label: 'real projects' },
      { n: 2, s: '', label: 'systems in production' },
      { n: 20, s: '+', label: 'technologies' },
      { n: 5, s: '', label: 'languages' },
    ],
    terminalHint: 'Try the terminal — type "help"',
  },
  work: {
    index: '02',
    title: 'Experience',
    company: 'Leops',
    role: 'Full Stack Developer',
    period: 'Jan 2026 — Present',
    place: 'Baku, Azerbaijan',
    also: { label: 'Also', name: 'Memorise', role: 'Developer', note: 'Team member', url: 'https://memorise.az/team' },
    items: [
      {
        name: 'Spec-Taxi',
        tag: 'Internal management system',
        url: 'https://db.spec.taxi',
        date: 'Jun 2026 — Present',
        points: [
          'Worked with the engineering team to design, build and release the new version of the platform.',
          'Developed front-end and back-end features based on requirements from the operations team.',
          'Refactored legacy code and fixed critical bugs, making the system faster and more reliable.',
        ],
      },
      {
        name: 'Assetra',
        tag: 'Asset & inventory management',
        date: 'Jul 2026 — Present',
        points: [
          'A new inventory management product for the company — React front end, Laravel back end.',
          'Team project, in active development.',
        ],
      },
      {
        name: 'leops.az',
        tag: 'Corporate website',
        url: 'https://leops.az',
        date: 'Jan 2026 — Present',
        points: [
          'Built and deployed the site end to end: responsive UI, back-end logic and dynamic content.',
          'Maintain it in production: performance optimization, bug fixes and security updates.',
        ],
      },
    ],
    across: 'Across projects: REST API integrations, slow SQL query optimization, server deployments, environment configuration and production troubleshooting.',
  },
  projects: {
    index: '03',
    title: 'Selected projects',
    sub: 'Personal projects built from scratch — some modelled on real products.',
    view: 'GitHub',
    live: 'Live demo',
    vis: { stage: 'STAGE', car: 'Car', ship: 'shipping', baku: 'Baku', less: 'Remove one', more: 'Add one', freeShip: 'Free delivery ✓', toFree: 'to free delivery', ingredients: 'ingredients' },
    items: [
      {
        name: 'az-job-radar',
        wip: true,
        vis: 'term',
        kind: 'Job market scraper',
        year: '2026',
        desc: 'An async scraper and data pipeline that collects IT vacancies from Azerbaijani job sites (boss.az, jobsearch.az), parses salaries and posting dates, and removes duplicates across sources. It respects robots.txt and rate limits and is tested against saved page fixtures. Next up: PostgreSQL storage, tech-demand analytics and a FastAPI REST API.',
        stack: ['Python', 'asyncio', 'httpx', 'BeautifulSoup', 'pytest', 'GitHub Actions'],
        url: 'https://github.com/saidmuradkhan/az-job-radar',
        features: ['Async scraping', 'robots.txt aware', 'Tested'],
        terminal: ['$ await collect()', 'boss.az        16 vacancies', 'jobsearch.az   90 vacancies', '# 106 unique · robots.txt respected'],
      },
      {
        name: 'cbar-rates',
        wip: true,
        vis: 'term',
        kind: 'Go microservice',
        year: '2026',
        desc: 'A small Go service that fetches the official daily exchange rates from the Central Bank of Azerbaijan, caches them in memory and serves them as a JSON API with a currency converter. Standard library only, tested with httptest.',
        stack: ['Go', 'net/http', 'encoding/xml', 'Docker'],
        url: 'https://github.com/saidmuradkhan/cbar-rates',
        features: ['REST API', 'In-memory cache', 'Converter'],
        terminal: ['# endpoints', '$ GET /rates', '$ GET /rates/USD', '$ GET /convert?from=USD&amount=1500'],
      },
      {
        name: 'jobtrack',
        wip: true,
        vis: 'term',
        kind: 'Full-stack app',
        year: '2026',
        desc: 'A job application tracker: browse vacancies collected by az-job-radar, save them in one click and move each application from "applied" to "offer" on a kanban board. Django REST Framework API with JWT auth and a React frontend; salaries are converted through cbar-rates.',
        stack: ['Django', 'Django REST Framework', 'JWT', 'PostgreSQL', 'React'],
        url: 'https://github.com/saidmuradkhan/jobtrack',
        features: ['Kanban board', 'JWT auth', '3 services'],
        terminal: ['# applications', 'Applied     ■ ■ ■ ■', 'Interview   ■ ■', 'Offer       ■'],
      },
      {
        name: 'iTicket',
        clone: true,
        vis: 'seatmap',
        kind: 'Ticketing platform',
        year: '2026',
        desc: 'An event ticketing platform modelled on iTicket.az: event search and filters, an interactive seat map, a cart with countdown timer and a user profile with tickets, orders, wallet and refunds. Real card payments via the Payriff API through a Node.js/Express service that keeps the secret key server-side and verifies payment status. Google sign-in, multi-language UI and dark mode.',
        stack: ['React', 'React Router', 'Context API', 'Node.js', 'Express', 'Payriff'],
        url: 'https://github.com/saidmuradkhan/Iticket',
        live: 'https://iticket.saidmuradkhan.dev',
        features: ['Seat map', 'Payriff payments', 'Google Auth'],
      },
      {
        name: 'Carify',
        clone: true,
        vis: 'route',
        kind: 'Car import',
        year: '2026',
        desc: 'A car import and shipping site modelled on carify-global.com: car catalog, shipping cost calculator, shipment tracking with Google Maps, wishlist, authentication and multi-language support.',
        stack: ['React', 'React Router', 'i18next', 'Axios', 'Google Maps API'],
        url: 'https://github.com/saidmuradkhan/Carify',
        live: 'https://carify.saidmuradkhan.dev',
        features: ['Cost calculator', 'Live tracking', 'i18n'],
      },
      {
        name: 'Zenvolt',
        vis: 'cart',
        kind: 'E-commerce store',
        year: '2026',
        desc: 'A responsive electronics store for a fictional Baku shop: search, category filters and sorting synced to the URL, product pages with specs and related items, a persistent cart drawer and wishlist, and a validated checkout flow with order confirmation.',
        stack: ['React', 'React Router', 'Context + useReducer', 'Tailwind CSS', 'localStorage'],
        url: 'https://github.com/saidmuradkhan/ecommerce',
        live: 'https://ecommerce.saidmuradkhan.dev',
        features: ['Persistent cart', 'URL-synced filters', 'Form validation'],
      },
      {
        name: 'Amber Lounge',
        vis: 'mixer',
        kind: 'Cocktail discovery',
        year: '2026',
        desc: 'A cocktail discovery app with a dark, amber-lit lounge design, powered by TheCocktailDB API: debounced search by name or ingredient, category and A–Z browsing, full recipe pages with ingredient thumbnails, favorites and a validated reservation form.',
        stack: ['React', 'React Router', 'Axios', 'Tailwind CSS', 'REST API'],
        url: 'https://github.com/saidmuradkhan/cocktail',
        live: 'https://cocktail.saidmuradkhan.dev',
        features: ['Live search', 'Favorites', 'Public API'],
      },
    ],
  },
  skills: {
    index: '04',
    title: 'Tools & skills',
    groups: { backend: 'Backend', frontend: 'Frontend', data: 'Databases', devops: 'DevOps & tools', other: 'Other languages' },
    langTitle: 'Languages I speak',
    langs: [
      { name: 'Azerbaijani', level: 'Native', v: 100 },
      { name: 'Turkish', level: 'C2', v: 95 },
      { name: 'English', level: 'B2', v: 70 },
      { name: 'Russian', level: 'A2', v: 30 },
      { name: 'German', level: 'A1', v: 15 },
    ],
  },
  edu: {
    index: '05',
    title: 'Education',
    items: [
      { when: '2024 — Now', what: 'Computer Science', where: 'Khazar University', note: 'Bachelor\'s (EQF 6)' },
      { when: '2025 — Now', what: 'Full Stack Web Development', where: 'Div Academy', note: 'React, Tailwind CSS, Node.js/Express, REST API design · Grade: 98/100' },
    ],
  },
  contact: {
    index: '06',
    kicker: 'Next project',
    title1: 'Let\'s build',
    title2: 'something.',
    text: 'A job offer, a project idea or just a hello — your message won\'t go unanswered.',
    copy: 'Copy',
    copied: 'Copied!',
    send: 'Write an email',
    local: 'Baku time',
    built: 'Built with love and lots of coffee',
    top: 'Back to top',
  },
  term: {
    welcome: 'said@portfolio:~$ Welcome! Type "help" to see the commands.',
    help: 'Commands: whoami · skills · projects · contact · hire · clear',
    whoami: 'Said Muradkhan — Full-Stack Developer @ Leops. Baku. Loves Laravel + React.',
    skills: 'PHP, Laravel, JavaScript, React, Node.js, Express, MySQL, PostgreSQL, Docker, Git',
    projects: 'Spec-Taxi · Assetra · leops.az · iTicket · Carify · Zenvolt · Amber Lounge',
    contact: 'saidmuradkhan414@gmail.com',
    hire: 'Great choice 😄 Taking you to the contact section...',
    unknown: 'Command not found: ',
  },
}

